name: Packaging 📦

on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
      version_name:
        required: false
        type: string

jobs:
  package:
    name: Run production build 🏗️
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.commit }}
          submodules: true

      - name: Setup node environment
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version-file: .nvmrc
          cache: npm
          check-latest: true

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Build native shell
        env:
          VERSION_NAME: ${{ inputs.version_name }}
        run: npm run build:nativeshell

      - name: Build web
        run: npm run build:web

      - name: Package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: package
          path: dist/package
